version: "3.5"

services:
  server:
    build: server/
    image: fastapi-server:latest
    hostname: fastapi-server
    environment:
      PORT: 8080

  client:
    build: client/
    image: fastapi-client:latest
    environment:
      PORT: 8080
      HANDLER_ADDRESS: http://fastapi-server:8080
    ports:
      - "8081:8080"
  
networks: 
  default:
    name: socketio-test
