version: "3.5"

services:
  server:
    build: server/
    image: service-a:latest
    environment:
      PORT: 8080

  client:
    build: server/
    image: service-b:latest
    environment:
      PORT: 8080
      HANDLER_ADDRESS: http://fastapi_socketio_example_server_1:8080
    ports:
      - "8081:8080"
  
networks: 
  default:
    external:
      name: socketio-test
