version: "3.5"

services:
  server:
    build: server/
    image: socketio-server:latest
    hostname: socketio-server
    environment:
      PORT: 8080

  client:
    build: client/
    image: socketio-client:latest
    environment:
      PORT: 8080
      HANDLER_ADDRESS: http://socketio-server:8080
    ports:
      - "8081:8080"
  
networks: 
  default:
    name: socketio-test
